### ISSUE TITLE
Featured request

### ISSUE THREAD

**Issue by Jimmi08** [CaMer0n/multisite#1]
To get it works on shared hosting where you have access only to one database and more installation is different only by prefix

**Comment by CaMer0n** [comment]
Looking into it.

**Comment by Jimmi08** [comment]
Thank you - or more databases and each one has different user.  What is easier.

**Comment by Jimmi08** [comment]
Thank you, it works

**Comment by CaMer0n** [comment]
Great! :+1:  Thanks.
